#+title: Node.js
Use to install [[https://nodejs.org][Node.js]]. This is based on the global [[file:template.org][template]].

* Usage
The script can be used by executing:
#+begin_src :tangle no
  . setup-nodejs.sh [-v VERSION]
#+end_src

** Parameters
*** VERSION
The version you want to install. Defaults to the [[*Default version][default version]].

* Implementation
#+begin_src shell :tangle src/setup-nodejs.sh :mkdirp yes :noweb yes :shebang #!/bin/sh :tangle-mode '#o644 :exports none
  <<template.org:lib()>>

  <<default_version>>
  <<export_vars>>
  <<restore_exported_vars>>
  <<installation_path>>
  <<is_installed>>
  <<installation_file>>
  <<install_installation_file>>
  <<download_url>>
  <<print_success_message>>

  __sp_main ${@}
#+end_src

** Global variables
*** Default version
Use a LTS:
#+name: default_version
#+begin_src shell
  __sp_default_version() {
      echo v20.14.0
  }
#+end_src

*** Exported variables
The ~PATH~ variable is exported. It must be saved and restored, if something goes wrong:
#+name: export_vars
#+begin_src shell
  __sp_export_vars() {
      echo "Add $(__sp_installation_path) to PATH"
      __SP_NODEJS_ORIGINAL_PATH="${PATH}"

      export PATH="$(__sp_installation_path):${PATH}"
  }
#+end_src

The corresponding reset function restores the ~PATH~ and deletes the backup, to clean up the environment:
#+name: restore_exported_vars
#+begin_src shell
  __sp_restore_exported_vars() {
      if [ -v __SP_NODEJS_ORIGINAL_PATH ]; then
	  export PATH="${__SP_NODEJS_ORIGINAL_PATH}"
	  unset __SP_NODEJS_ORIGINAL_PATH
      fi
  }
#+end_src

*** Installation path
The installation differs, depending on the target OS. Windows with MingW and Linux are supported:
#+name: installation_path
#+begin_src shell
  __sp_installation_path() {
      case "$(uname -s)" in
	  CYGWIN*|MINGW*|MSYS*)
	      echo $__sp_installation_base_dir/node-$__sp_version-win-x64
	      ;;
	  ,*)
	      echo $__sp_installation_base_dir/node-$__sp_version-linux-x64/bin
	      ;;
      esac
  }
#+end_src

** Check, if wanted version is installed
Before starting the installation, check if the wanted version is already installed:
#+name: is_installed
#+begin_src shell
  __sp_is_installed() {
      node --version 2>/dev/null &&
	  (node --version 2>&1 | grep $__sp_version)
  }
#+end_src

** Install wanted version
The installation file is specific to the target OS:

*** Installation file
#+name: installation_file
#+begin_src shell
  __sp_installation_file() {
      case "$(uname -s)" in
	  CYGWIN*|MINGW*|MSYS*)
	      echo node-$__sp_version-win-x64.zip
	      ;;
	  ,*)
	      echo node-$__sp_version-linux-x64.tar.xz
	      ;;
      esac
  }
#+end_src

*** Install installation file
The installation of the local installation file is specific to the target OS:
#+name: install_installation_file
#+begin_src shell
  __sp_install_installation_file() {
      local trgt_dir=$(dirname $(__sp_installation_path))

      case "$(uname -s)" in
	  CYGWIN*|MINGW*|MSYS*)
	      unzip -oq $(local_installation_file_path) -d $trgt_dir
	      ;;
	  ,*)
	      tar Jxf $(local_installation_file_path) -C $__sp_installation_base_dir
	      ;;
      esac
  }
#+end_src

*** Download URL
#+name: download_url
#+begin_src shell
  __sp_download_url() {
      echo https://nodejs.org/dist/$__sp_version/$(__sp_installation_file)
  }
#+end_src

** Print success message
The success message prints the version of the current Node.js installation:
#+name: print_success_message
#+begin_src shell
  __sp_print_success_message() {
      node -v
  }
#+end_src

* Tests
** Execute
Execute OS independent tests:
#+begin_src shell
  test/bats/bin/bats -t test/test-nodejs.bats
#+end_src
#+begin_src bats :tangle test/test-nodejs.bats :mkdirp yes :noweb strip-export :shebang #!/usr/bin/env bats :tangle-mode '#o644 :exports none
  __SP_TESTEE=src/setup-nodejs.sh

  <<setup>>
  <<teardown>>

  <<Environment must be clean after execution if succeeds with default version>>
  <<Environment must be clean after execution if succeeds with given version>>
  <<Environment must be clean after execution if installation fails>>
  <<Should only print success message if version is already installed>>
  <<Should not alter environment if installation fails>>
  <<Must print error message if remote installation file not found>>
  <<Should try download if local installation file not exists>>
  <<Should try download if remote installation file exists>>
#+end_src

Execute tests specific for Linux:
#+begin_src shell
  test/bats/bin/bats -t test/test-nodejs.linux.bats
#+end_src
#+begin_src bats :tangle test/test-nodejs.linux.bats :mkdirp yes :noweb strip-export :shebang #!/usr/bin/env bats :tangle-mode '#o644 :exports none
  __SP_TESTEE=src/setup-nodejs.sh

  <<setup>>
  <<teardown>>

  <<Must print versions to install with default version using Linux>>
  <<Must print versions to install with given version using Linux>>
  <<Should export variables if succeeds with default version using Linux>>
  <<Should export variables if succeeds with given version using Linux>>
  <<Should not alter environment if version is already installed using Linux>>
  <<Must print success message if installation succeeds with default version using Linux>>
  <<Must print success message if installation succeeds with given version using Linux>>
  <<Should not try download if local installation file exists using Linux>>
#+end_src

Execute tests specific for Windows:
#+begin_src shell
  test/bats/bin/bats -t test/test-nodejs.win.bats
#+end_src
#+begin_src bats :tangle test/test-nodejs.win.bats :mkdirp yes :noweb strip-export :shebang #!/usr/bin/env bats :tangle-mode '#o644 :exports none
  __SP_TESTEE=src/setup-nodejs.sh

  <<setup>>
  <<teardown>>

  <<Must print versions to install with default version using Windows>>
  <<Must print versions to install with given version using Windows>>
  <<Should export variables if succeeds with default version using Windows>>
  <<Should export variables if succeeds with given version using Windows>>
  <<Should not alter environment if version is already installed using Windows>>
  <<Must print success message if installation succeeds with default version using Windows>>
  <<Must print success message if installation succeeds with given version using Windows>>
  <<Should not try download if local installation file exists using Windows>>
#+end_src

Each test needs a setup, which loads the necessary Bats libraries:
- [[https://github.com/bats-core/bats-support][bats-support]]
- [[https://github.com/bats-core/bats-assert][bats-assert]]
- [[https://github.com/bats-core/bats-file][bats-file]]

Furthermore, the exported variables are backed up. In this case at least the ~PATH~:
#+name: setup
#+begin_src bats
  setup() {
    load 'test_helper/bats-support/load'
    load 'test_helper/bats-assert/load'
    load 'test_helper/bats-file/load'

    SPT_ORIGINAL_PATH="$PATH"
  }
#+end_src

To clean up, the exported variables are reset to its saved values after each test:
#+name: teardown
#+begin_src bats
  teardown() {
      PATH="$SPT_ORIGINAL_PATH"
  }
#+end_src

** Test cases

*** Must print version and path to install
If wanted version is not the current, print the version to be installed and the path to be added.
**** With default version
***** Using Linux
#+name: Must print versions to install with default version using Linux
#+begin_src bats
  @test "Must print versions to install with default version using Linux" {
      run . $__SP_TESTEE

      assert_line 'Install version: v20.14.0'
      assert_line "Add $HOME/opt/node-v20.14.0-linux-x64/bin to PATH"

      rm /tmp/node-v20.14.0-*
  }
#+end_src

***** Using Windows
#+name: Must print versions to install with default version using Windows
#+begin_src bats
  @test "Must print versions to install with default version using Windows" {
      run . $__SP_TESTEE

      assert_line 'Install version: v20.14.0'
      assert_line "Add $HOME/opt/node-v20.14.0-win-x64 to PATH"

      rm /tmp/node-v20.14.0-*
  }
#+end_src

**** With given version

***** Using Linux
#+name: Must print versions to install with given version using Linux
#+begin_src bats
  @test "Must print versions to install with given version using Linux" {
      run .  $__SP_TESTEE -v v18.20.3

      assert_line 'Install version: v18.20.3'
      assert_line "Add $HOME/opt/node-v18.20.3-linux-x64/bin to PATH"

      rm /tmp/node-v18.20.3-*
  }
#+end_src

***** Using Windows
#+name: Must print versions to install with given version using Windows
#+begin_src bats
  @test "Must print versions to install with given version using Windows" {
      run .  $__SP_TESTEE -v v18.20.3

      assert_line 'Install version: v18.20.3'
      assert_line "Add $HOME/opt/node-v18.20.3-win-x64 to PATH"

      rm /tmp/node-v18.20.3-*
  }
#+end_src

*** Environment must be clean after execution

**** If succeeds with default version
After the script has run without a given version, the newly introduced global variables shall not be set and ~$OPTIND~ must be ~1~:
#+name: Environment must be clean after execution if succeeds with default version
#+begin_src bats
  @test "Environment must be clean after execution if succeeds with default version" {
      . $__SP_TESTEE

      assert_equal $OPTIND 1
      assert [ -z $__sp_installation_base_dir ]
      assert [ -z $__sp_version ]

      rm /tmp/node-v20.14.0-*
  }
#+end_src

**** If succeeds with given version
After the script has run with a given version, the newly introduced global variables shall not be set and ~$OPTIND~ must be ~1~:
#+name: Environment must be clean after execution if succeeds with given version
#+begin_src bats
  @test "Environment must be clean after execution if succeeds with given version" {
      . $__SP_TESTEE -v v18.20.3

      assert_equal $OPTIND 1
      assert [ -z $__sp_installation_base_dir ]
      assert [ -z $__sp_version ]

      rm /tmp/node-v18.20.3-*
  }
#+end_src

**** If installation fails
After the script failed, the newly introduced global variables shall not be set and ~$OPTIND~ must be ~1~:
#+name: Environment must be clean after execution if installation fails
#+begin_src bats
  @test "Environment must be clean after execution if installation fails" {
      . $__SP_TESTEE -v installation_fail || assert_equal $? 127

      assert_equal $OPTIND 1
      assert [ -z $__sp_installation_base_dir ]
      assert [ -z $__sp_version ]
  }
#+end_src

*** Should export variables
The exported ~$PATH~ must be extended with the wanted version.

**** If succeeds with default version

***** Using Linux
#+name: Should export variables if succeeds with default version using Linux
#+begin_src bats
  @test "Should export variables if succeeds with default version using Linux" {
      . $__SP_TESTEE

      assert_equal "$PATH" "$HOME/opt/node-v20.14.0-linux-x64/bin:$SPT_ORIGINAL_PATH"

      rm /tmp/node-v20.14.0-linux-x64.tar.xz
  }
#+end_src

***** Using Windows
#+name: Should export variables if succeeds with default version using Windows
#+begin_src bats
  @test "Should export variables if succeeds with default version using Windows" {
      . $__SP_TESTEE

      assert_equal "$PATH" "$HOME/opt/node-v20.14.0-win-x64:$SPT_ORIGINAL_PATH"

      rm /tmp/node-v20.14.0-win-x64.zip
  }
#+end_src

**** If succeeds with given version

***** Using Linux
#+name: Should export variables if succeeds with given version using Linux
#+begin_src bats
  @test "Should export variables if succeeds with given version using Linux" {
      . $__SP_TESTEE -v v18.20.3

      assert_equal "$PATH" "$HOME/opt/node-v18.20.3-linux-x64/bin:$SPT_ORIGINAL_PATH"

      rm /tmp/node-v18.20.3-linux-x64.tar.xz
  }
#+end_src

***** Using Windows
#+name: Should export variables if succeeds with given version using Windows
#+begin_src bats
  @test "Should export variables if succeeds with given version using Windows" {
      . $__SP_TESTEE -v v18.20.3

      assert_equal "$PATH" "$HOME/opt/node-v18.20.3-win-x64:$SPT_ORIGINAL_PATH"

      rm /tmp/node-v18.20.3-win-x64.zip
  }
#+end_src

*** Should only print success message, if version is already installed
If the given (or default) version is already installed, only a success message should be shown:
#+name: Should only print success message if version is already installed
#+begin_src bats
  @test "Should only print success message if version is already installed" {
      . $__SP_TESTEE
      rm /tmp/node-v20.14.0-*

      run . $__SP_TESTEE

      refute_line -p "Add $HOME/opt/"
      refute_line -p 'Install version: '
      assert_line 'v20.14.0'

      assert_file_not_exists /tmp/node-v20.14.0-*
  }
#+end_src

*** Should not alter environment, if version is already installed
If the given (or default) version is already installed, the environment should not be altered:

**** Using Linux
#+name: Should not alter environment if version is already installed using Linux
#+begin_src bats
  @test "Should not alter environment if version is already installed using Linux" {
      . $__SP_TESTEE
      assert_equal "$PATH" "$HOME/opt/node-v20.14.0-linux-x64/bin:$SPT_ORIGINAL_PATH"
      rm /tmp/node-v20.14.0-linux-x64.tar.xz

      . $__SP_TESTEE

      assert_equal $OPTIND 1
      assert [ -z $__sp_installation_base_dir ]
      assert [ -z $__sp_version ]
      assert_equal "$PATH" "$HOME/opt/node-v20.14.0-linux-x64/bin:$SPT_ORIGINAL_PATH"

      assert_file_not_exists /tmp/node-v20.14.0-linux-x64.tar.xz
  }
#+end_src

**** Using Windows
#+name: Should not alter environment if version is already installed using Windows
#+begin_src bats
  @test "Should not alter environment if version is already installed using Windows" {
      . $__SP_TESTEE
      assert_equal "$PATH" "$HOME/opt/node-v20.14.0-win-x64:$SPT_ORIGINAL_PATH"
      rm /tmp/node-v20.14.0-win-x64.zip

      . $__SP_TESTEE

      assert_equal $OPTIND 1
      assert [ -z $__sp_installation_base_dir ]
      assert [ -z $__sp_version ]
      assert_equal "$PATH" "$HOME/opt/node-v20.14.0-win-x64:$SPT_ORIGINAL_PATH"

      assert_file_not_exists /tmp/node-v20.14.0-win-x64.zip
  }
#+end_src

*** Should not alter environment, if installation fails
After the script failed, the exported ~$PATH~ must not be altered:
#+name: Should not alter environment if installation fails
#+begin_src bats
  @test "Should not alter environment if installation fails" {
      . $__SP_TESTEE -v installation_fail || assert_equal $? 127

      assert_equal "$PATH" "$SPT_ORIGINAL_PATH"
  }
#+end_src

*** Must print success message, if installation succeeds
If successful, a success message must be printed.

**** With default version

***** Using Linux
#+name: Must print success message if installation succeeds with default version using Linux
#+begin_src bats
  @test "Must print success message if installation succeeds with default version using Linux" {
      run . $__SP_TESTEE

      assert_line 'v20.14.0'

      rm /tmp/node-v20.14.0-linux-x64.tar.xz
  }
#+end_src

***** Using Windows
#+name: Must print success message if installation succeeds with default version using Windows
#+begin_src bats
  @test "Must print success message if installation succeeds with default version using Windows" {
      run . $__SP_TESTEE

      assert_line 'v20.14.0'

      rm /tmp/node-v20.14.0-win-x64.zip
  }
#+end_src

**** With given version

***** Using Linux
#+name: Must print success message if installation succeeds with given version using Linux
#+begin_src bats
  @test "Must print success message if installation succeeds with given version using Linux" {
      run . $__SP_TESTEE -v v18.20.3

      assert_line 'v18.20.3'

      rm /tmp/node-v18.20.3-linux-x64.tar.xz
  }
#+end_src

***** Using Windows
#+name: Must print success message if installation succeeds with given version using Windows
#+begin_src bats
  @test "Must print success message if installation succeeds with given version using Windows" {
      run . $__SP_TESTEE -v v18.20.3

      assert_line 'v18.20.3'

      rm /tmp/node-v18.20.3-win-x64.zip
  }
#+end_src

*** Must print error message, if remote installation file not found
#+name: Must print error message if remote installation file not found
#+begin_src bats
  @test "Must print error message if remote installation file not found" {
      run . $__SP_TESTEE -v download_fail

      assert_line 'Install version: download_fail'
      assert_line -e 'Local installation file not found: /tmp/node-download_fail-.*\. Try, download new one'
      assert_line 'ERROR: No remote installation file found. Abort'
      assert_file_not_exists /tmp/node-download_fail-*
  }
#+end_src

*** Should try download

**** If local installation file not exists
#+name: Should try download if local installation file not exists
#+begin_src bats
  @test "Should try download if local installation file not exists" {
      run . $__SP_TESTEE

      assert_line -e 'Local installation file not found: /tmp/node-v20\.14\.0-.*\. Try, download new one'
      assert_line 'Download installation file'

      rm /tmp/node-v20.14.0-*
  }
#+end_src

**** If remote installation file exists
#+name: Should try download if remote installation file exists
#+begin_src bats
  @test "Should try download if remote installation file exists" {
      run . $__SP_TESTEE

      assert_line 'Download installation file'

      rm /tmp/node-v20.14.0-*
   }
#+end_src

*** Should not try download, if local installation file exists

**** Using Linux
#+name: Should not try download if local installation file exists using Linux
#+begin_src bats
  @test "Should not try download if local installation file exists using Linux" {
      touch /tmp/node-v20.14.0-linux-x64.tar.xz

      run . $__SP_TESTEE

      refute_line 'Local installation file not found: /tmp/node-v20.14.0-linux-x64.tar.xz. Try, download new one'
      refute_line 'Download installation file'

      rm /tmp/node-v20.14.0-linux-x64.tar.xz
  }
#+end_src

**** Using Windows
#+name: Should not try download if local installation file exists using Windows
#+begin_src bats
  @test "Should not try download if local installation file exists using Windows" {
      touch /tmp/node-v20.14.0-win-x64.zip

      run . $__SP_TESTEE

      refute_line 'Local installation file not found: /tmp/node-v20.14.0-win-x64.zip. Try, download new one'
      refute_line 'Download installation file'

      rm /tmp/node-v20.14.0-win-x64.zip
  }
#+end_src
