#+title: Node.js
Use to install [[https://nodejs.org][Node.js]] (based on the global [[file:template.org][template]]).

* Usage
#+begin_example
  $ . setup-nodejs.sh [-v VERSION]
#+end_example

** Version
The version you want to install. Defaults to the [[*Default version][default version]].

* Implementation
#+begin_src shell :tangle src/setup-nodejs.sh :mkdirp yes :noweb yes :shebang #!/bin/sh :tangle-mode '#o644 :exports none
  <<template.org:lib()>>

  <<default_version>>
  <<export_vars>>
  <<restore_exported_vars>>
  <<installation_path>>
  <<is_installed>>
  <<installation_file>>
  <<install_installation_file>>
  <<download_url>>
  <<print_success_message>>

  main ${@}
#+end_src

** Global variables
*** Default version
Use the current LTS:
#+name: default_version
#+begin_src shell
  default_version() {
      echo v20.14.0
  }
#+end_src

*** Exported variables
The ~PATH~ variable is exported. It must be saved and restored, if something goes wrong:
#+name: export_vars
#+begin_src shell
  export_vars() {
      echo "Adding $(installation_path) to PATH"
      SETUP_NODEJS_ORIGINAL_PATH="${PATH}"

      export PATH="$(installation_path):${PATH}"
  }
#+end_src

The corresponding reset function restores the ~PATH~ and deletes the backup, to clean up the environment:
#+name: restore_exported_vars
#+begin_src shell
  restore_exported_vars() {
      if [ -v SETUP_TMPL_ORIGINAL_PATH ]; then
	  export PATH="${SETUP_NODEJS_ORIGINAL_PATH}"
	  unset SETUP_NODEJS_ORIGINAL_PATH
      fi
  }
#+end_src

*** Installation path
The installation differs, depending on the target OS. Windows with MingW and Linux are supported:
#+name: installation_path
#+begin_src shell
  installation_path() {
      case "$(uname -s)" in
	  CYGWIN*|MINGW*|MSYS*)
	      echo $INSTALLATION_BASE_DIR/node-$VERSION-win-x64
	      ;;
	  ,*)
	      echo $INSTALLATION_BASE_DIR/node-$VERSION-linux-x64/bin
	      ;;
      esac
  }
#+end_src

** Check, if wanted version is installed
Before starting the installation, check if the wanted version is already installed:
#+name: is_installed
#+begin_src shell
  is_installed() {
      node --version 2>/dev/null &&
	  (node --version 2>&1 | grep $VERSION)
  }
#+end_src

** Install wanted version
The installation file is specific to the target OS:

*** Installation file
#+name: installation_file
#+begin_src shell
  installation_file() {
      case "$(uname -s)" in
	  CYGWIN*|MINGW*|MSYS*)
	      echo node-$VERSION-win-x64.zip
	      ;;
	  ,*)
	      echo node-$VERSION-linux-x64.tar.xz
	      ;;
      esac
  }
#+end_src

*** Install installation file
The installation of the installation file is specific to the target OS:
#+name: install_installation_file
#+begin_src shell
  install_installation_file() {
      local trgt_dir=$(dirname $(installation_path))

      case "$(uname -s)" in
	  CYGWIN*|MINGW*|MSYS*)
	      unzip -q $(local_installation_file_path) -d $trgt_dir
	      ;;
	  ,*)
	      tar Jxf $(local_installation_file_path) -C $INSTALLATION_BASE_DIR
	      ;;
      esac
  }
#+end_src

*** Download URL
#+name: download_url
#+begin_src shell
  download_url() {
      echo https://nodejs.org/dist/$VERSION/$(installation_file)
  }
#+end_src

** Print success message
The success message prints the version of the current Node.js installation:
#+name: print_success_message
#+begin_src shell
  print_success_message() {
      node -v
  }
#+end_src

* Tests
** Execute
#+begin_src shell
  test/bats/bin/bats -t test/test-nodejs.bats
#+end_src

#+begin_src bats :tangle test/test-nodejs.bats :mkdirp yes :noweb strip-export :shebang #!/usr/bin/env bats :exports none
  SPT_SCRIPT=src/setup-nodejs.sh

  <<setup>>
  <<teardown>>


  <<Must print success message>>
  <<Must print error message if remote installation file not found>>
  <<Environment must be clean after execution if installation fails>>
  <<Exported variables must not be set if installation fails>>

  <<Should try download if local installation file not exists>>
  <<Should not try download if local installation file exists>>
  <<Should try download if remote installation file exists>>



  <<Should only output success message if version is already installed>>
#+end_src
#+begin_src bats :tangle test/test-nodejs.linux.bats :mkdirp yes :noweb strip-export :shebang #!/usr/bin/env bats :exports none
  SPT_SCRIPT=src/setup-nodejs.sh

  <<setup>>
  <<teardown>>

  <<Environment must be clean after execution if succeeds with default version using Linux>>
  <<Environment must be clean after execution if succeeds with given version using Linux>>
  <<Must print versions to install with default version using Linux>>
  <<Must print versions to install with given version using Linux>>
  <<Exported variables must be set if succeeds with default version using Linux>>
  <<Exported variables must be set if succeeds with given version using Linux>>



  <<Should not set variables if version is already installed using Linux>>
#+end_src
#+begin_src bats :tangle test/test-nodejs.win.bats :mkdirp yes :noweb strip-export :shebang #!/usr/bin/env bats :exports none
  SPT_SCRIPT=src/setup-nodejs.sh

  <<setup>>
  <<teardown>>

  <<Exported variables must be set if succeeds with default version using Windows>>
  <<Exported variables must be set if succeeds with given version using Windows>>
#+end_src


Each test needs a setup, which loads the necessary Bats libraries:
- [[https://github.com/bats-core/bats-support][bats-support]]
- [[https://github.com/bats-core/bats-assert][bats-assert]]
- [[https://github.com/bats-core/bats-file][bats-file]]

Furthermore, the exported variables are backed up. In this case at least the ~PATH~:
#+name: setup
#+begin_src bats
  setup() {
    load 'test_helper/bats-support/load'
    load 'test_helper/bats-assert/load'
    load 'test_helper/bats-file/load'

    SPT_ORIGINAL_PATH="$PATH"
  }
#+end_src

To clean up, the exported variables are reset to its saved values after each test:
#+name: teardown
#+begin_src bats
  teardown() {
      PATH="$SPT_ORIGINAL_PATH"
  }
#+end_src

** Test cases

*** Must print versions to install

**** With default version using Linux
#+name: Must print versions to install with default version using Linux
#+begin_src bats
  @test "Must print versions to install with default version using Linux" {
      run . $SPT_SCRIPT

      assert_line 'Install version: v20.14.0'

      rm /tmp/node-v20.14.0-linux-x64.tar.xz
  }
#+end_src

**** With given version using Linux
#+name: Must print versions to install with given version using Linux
#+begin_src bats
  @test "Must print versions to install with given version" {
      run .  $SPT_SCRIPT -v v18.20.3

      assert_line 'Install version: v18.20.3'

      rm /tmp/node-v18.20.3-linux-x64.tar.xz
  }
#+end_src

*** Environment must be clean after execution

**** If succeeds with default version
After the script has run without a given version, the newly introduced global variables shall not be set and ~$OPTIND~ must be ~1~:
#+name: Environment must be clean after execution if succeeds with default version using Linux
#+begin_src bats
  @test "Environment must be clean after execution if succeeds with default version using Linux" {
      . $SPT_SCRIPT

      assert_equal $OPTIND 1
      assert [ -z $INSTALLATION_BASE_DIR ]
      assert [ -z $VERSION ]

      rm /tmp/node-v20.14.0-linux-x64.tar.xz
  }
#+end_src

**** If succeeds with given version
After the script has run with a given version, the newly introduced global variables shall not be set and ~$OPTIND~ must be ~1~:
#+name: Environment must be clean after execution if succeeds with given version using Linux
#+begin_src bats
  @test "Environment must be clean after execution if succeeds with given version using Linux" {
      . $SPT_SCRIPT -v v18.20.3

      assert_equal $OPTIND 1
      assert [ -z $INSTALLATION_BASE_DIR ]
      assert [ -z $VERSION ]

      rm /tmp/node-v18.20.3-linux-x64.tar.xz
  }
#+end_src

*** Exported variables must be set
The exported ~$PATH~ must be extended with the wanted version.

**** If succeeds with default version

***** Using Linux
#+name: Exported variables must be set if succeeds with default version using Linux
#+begin_src bats
  @test "Exported variables must be set if succeeds with default version using Linux" {
      . $SPT_SCRIPT

      assert_equal "$PATH" "$HOME/opt/node-v20.14.0-linux-x64/bin:$SPT_ORIGINAL_PATH"

      rm /tmp/node-v20.14.0-linux-x64.tar.xz
  }
#+end_src

***** Using Windows
#+name: Exported variables must be set if succeeds with default version using Windows
#+begin_src bats
  @test "Exported variables must be set if succeeds with default version using Windows" {
      . $SPT_SCRIPT

      assert_equal "$PATH" "$HOME/opt/node-v20.14.0-win-x64:$SPT_ORIGINAL_PATH"

      rm /tmp/node-v20.14.0-win-x64.zip
  }
#+end_src

**** If succeeds with given version

***** Using Linux
#+name: Exported variables must be set if succeeds with given version using Linux
#+begin_src bats
  @test "Exported variables must be set if succeeds with given version using Linux" {
      . $SPT_SCRIPT -v v18.20.3

      assert_equal "$PATH" "$HOME/opt/node-v18.20.3-linux-x64/bin:$SPT_ORIGINAL_PATH"

      rm /tmp/node-v18.20.3-linux-x64.tar.xz
  }
#+end_src

***** Using Windows
#+name: Exported variables must be set if succeeds with given version using Windows
#+begin_src bats
  @test "Exported variables must be set if succeeds with given version using Windows" {
      . $SPT_SCRIPT -v v18.20.3

      assert_equal "$PATH" "$HOME/opt/node-v18.20.3-win-x64:$SPT_ORIGINAL_PATH"

      rm /tmp/node-v18.20.3-win-x64.zip
  }
#+end_src

*** Should only output success message, if version is already installed
If the given (or default) version is already installed, only a success message should be shown:
#+name: Should only output success message if version is already installed
#+begin_src bats
  @test "Should only output success message if version is already installed" {
      . $SPT_SCRIPT
      # assert_line "Adding $HOME/opt/node-v20.14.0-linux-x64/bin to PATH"
      # assert_line "Install version: v20.14.0"
      # assert_line "v20.14.0"

      rm /tmp/node-v20.14.0-linux-x64.tar.xz

      run . $SPT_SCRIPT

      refute_line -p "Adding $HOME/opt/"
      refute_line -p "Install version: "
      assert_line "v20.14.0"

      assert_file_not_exists /tmp/node-v20.14.0-linux-x64.tar.xz
  }
#+end_src

*** Should not set variables, if version is already installed
**** Using Linux
If the given (or default) version is already installed, the environment should not be altered:
#+name: Should not set variables if version is already installed using Linux
#+begin_src bats
  @test "Should not set variables if version is already installed using Linux" {
      . $SPT_SCRIPT
      assert_equal $OPTIND 1
      assert [ -z $INSTALLATION_BASE_DIR ]
      assert [ -z $VERSION ]
      assert_equal "$PATH" "$HOME/opt/node-v20.14.0-linux-x64/bin:$SPT_ORIGINAL_PATH"

      rm /tmp/node-v20.14.0-linux-x64.tar.xz

      . $SPT_SCRIPT

      assert_equal $OPTIND 1
      assert [ -z $INSTALLATION_BASE_DIR ]
      assert [ -z $VERSION ]
      assert_equal "$PATH" "$HOME/opt/node-v20.14.0-linux-x64/bin:$SPT_ORIGINAL_PATH"

      assert_file_not_exists /tmp/node-v20.14.0-linux-x64.tar.xz
  }
#+end_src
