#+title: Template
* Usage
#+begin_example
  $ . set-template.sh [-v VERSION]
#+end_example
** Version
The version you want to install. Defaults to the [[*Default version][default version]].

** Overriding of functions
The template can be included into the software specific scripts, where specific functions can be overridden.
*NOTE*: By including scripts, you have to be careful, with execution of scripts, since these are executed during the inclusion and therefore before anything else!

#+begin_src shell :tangle no
  f1() {
      echo "Foo f1: To override"
  }

  f2() {
      echo "Foo f2: Not to override"
  }

  # To override
  main() {
      f1
      f2
  }

  main
#+end_src
#+begin_src shell :tangle no
  . $(dirname ${BASH_SOURCE[0]})/foo.sh

  f1() {
      echo "Bar f1: To override"
  }

  f3() {
      f2
      echo "Bar f3: Not to override"
  }

  main() {
      f1
      f3
  }

  main
#+end_src

* Implementation
1. Set global variables.
2. Override global variables given by options.
3. Reset PATH and other installation relevant exported variables.
4. Check, whether the wanted version is already installed.
5. If not, install the wanted version
6. Clean up the global variables after installation, but not the exported ones.
7. Print success message

If something goes wrong, abort. This means, restore the PATH and other global variables:
#+name: main
#+begin_src shell
  main() {
      init_global_vars
      set_vars_from_opts ${@}

      if ! is_installed; then
	  echo "Start installation"
	  restore_exported_vars
	  export_vars
	  install || abort
      fi

      reset_global_vars
      print_success_message
  }
#+end_src
#+name: lib
#+begin_src org :noweb yes :exports none
  <<default_version>>
  <<init_global_vars>>
  <<reset_global_vars>>
  <<set_vars_from_opts>>
  <<installation_path>>
  <<export_vars>>
  <<restore_exported_vars>>
  <<abort>>
  <<installation_file>>
  <<local_installation_file_path>>
  <<is_installed>>
  <<download_url>>
  <<remote_installation_file_exists>>
  <<download_installation_file>>
  <<install>>
  <<install_installation_file>>
  <<print_success_message>>
  <<main>>
#+end_src
#+begin_src shell :tangle src/setup-template.sh :mkdirp yes :noweb yes :shebang #!/bin/sh :tangle-mode '#o644 :exports none
  <<lib>>

  main ${@}
#+end_src

** Global variables
Each script uses some global variables, like the version to install. These have to be initialized for each run of the script. The initialization of this variables might be the same for all scripts. The only exception is the definition of the [[Default version][default version]], which is described later:
#+name: init_global_vars
#+begin_src shell
  init_global_vars() {
      VERSION=$(default_version)
      INSTALLATION_BASE_DIR=$HOME/opt
      # Reset OPTIND, if getopts was used before
      OPTIND=1
  }
#+end_src

The reset of global variables depends on the initialization. It is necessary to clean up, after the script ran successful or was aborted, because of an error. If ~init_global_vars~ was adopted in a script,  ~reset_global_vars~ variables might need to be adjusted as well:
#+name: reset_global_vars
#+begin_src shell
  reset_global_vars() {
      unset VERSION
      unset INSTALLATION_BASE_DIR
      # Reset OPTIND for future use of getopts
      OPTIND=1
  }
#+end_src

*** Default version
Since the strings for version (and therefore default version) are specific to the software, at least the function retrieving the default version has to be adapted in the particular scripts:
#+name: default_version
#+begin_src shell
  default_version() {
      echo tmpl_default-version
  }
#+end_src

*** Options
To pass options (like the version to be installed) to the scripts /getopts/ is used:
#+name: set_vars_from_opts
#+begin_src shell
  set_vars_from_opts() {
      while getopts v: opt; do
	  case $opt in
	      v) VERSION=$OPTARG
		 ;;
	  esac
      done
  }
#+end_src
At least the version needs to be set, but other scripts might need additional options. Therefore this method might be overridden.

*** Exported variables
The ~PATH~ variable and every other global variable, which is exported by the scripts might exist before the script is run and therefore must be saved and restored, if something goes wrong. In the following example, the ~PATH~ is saved before the new one is exported:
#+name: export_vars
#+begin_src shell
  export_vars() {
      echo "Adding $(installation_path) to PATH"
      SETUP_TMPL_ORIGINAL_PATH="${PATH}"

      export PATH="$(installation_path):${PATH}"
  }
#+end_src
*NOTE*: It is important to have an unique name for the backup variables!

The corresponding reset function restores the ~PATH~ and deletes the backup, to clean up the environment:
#+name: restore_exported_vars
#+begin_src shell
  restore_exported_vars() {
      if [ -v SETUP_TMPL_ORIGINAL_PATH ]; then
	  export PATH="${SETUP_TMPL_ORIGINAL_PATH}"
	  unset SETUP_TMPL_ORIGINAL_PATH
      fi
  }
#+end_src

*** Installation path
Since the installation path might be different, depending on the target OS and the software, it is declared as a function, which can be overridden:
#+name: installation_path
#+begin_src shell
  installation_path() {
      echo $INSTALLATION_BASE_DIR/tmpl-$VERSION
  }
#+end_src
** Check, if wanted version is installed
Before starting the installation, check if the wanted version is already installed. This should usually execute the wanted command and check the output for the correct version. In this template this is just a mock, which returns true, if the given version is ~installed~:
#+name: is_installed
#+begin_src shell
  is_installed() {
      case "$VERSION" in
	  installed) return 0
	      ;;
	  ,*) return 1
	      ;;
      esac
  }
#+end_src

** Install wanted version
If the wanted version is not installed, start the installation. This includes the following steps:
1. Check if an installation file for the current OS is present.
   1. If not, download correct installation file and proceed with next step. If no download file could be found, abort installation with an error message.
2. Install version with this installation file.
#+name: install
#+begin_src shell
  install() {
      echo "Install version: $VERSION"

      if [ ! -f $(local_installation_file_path) ]; then
	  echo "Local installation file not found: $(local_installation_file_path). Try, download new one"
	  if remote_installation_file_exists; then
	      download_installation_file
	  else
	      echo "ERROR: No remote installation file found. Abort"
	      abort
	  fi
      fi
      install_installation_file
   }
#+end_src

*** Installation file
The name of the installation file is specific to the software, its version and the target OS. Therefore a specific implementation is needed. For the template a dummy is used:
#+name: installation_file
#+begin_src shell
  installation_file() {
      echo installation.file
  }
#+end_src

*** Local installation file path
The path to the local installation file. The default location is in the ~/tmp/~ directory:
#+name: local_installation_file_path
#+begin_src shell
  local_installation_file_path() {
      echo /tmp/$(installation_file)
  }
#+end_src

*** Install installation file
The installation of the local installation file is specific to the software. For the template a dummy is used:
#+name: install_installation_file
#+begin_src shell
  install_installation_file() {
      echo "Install installation file"
	  case "$VERSION" in
	  installation_fail) return 1
	     ;;
	  ,*) return 0
	     ;;
      esac
  }
#+end_src

*** Check, if remote installation file exists
Before downloading the installation file, check if it exists:
#+name: remote_installation_file_exists
#+begin_src shell
  remote_installation_file_exists() {
      curl -sIf $(download_url) >/dev/null
  }
#+end_src

*** Download URL
The download URL is specific to the software. For the template a dummy implementation is used:
#+name: download_url
#+begin_src shell
  download_url() {
      case "$VERSION" in
	  download_fail) echo https://github.com/aaron-kunde/setup-project/blob/main/non-existing.file
	     ;;
	  ,*) echo https://github.com/aaron-kunde/setup-project/blob/main/README.org
	     ;;
      esac
  }
#+end_src

*** Download installation file
If a remote installation file was found, download it:
#+name: download_installation_file
#+begin_src shell
  download_installation_file() {
      echo "Download installation file"
      curl $(download_url) -o $(local_installation_file_path)
  }
#+end_src

** Abort installation
During the installation process, several errors can occurs, which cause the need to abort the installation process. If the process needs to be aborted, all global variables need to be reset, as if the installation process never had been started:
#+name: abort
#+begin_src shell
  abort() {
      restore_exported_vars
      reset_global_vars

      return 0
  }
#+end_src

** Print success message
The success message dependes of the installed software and must be implmenented specific:
#+name: print_success_message
#+begin_src shell
  print_success_message() {
      echo "TMPL successfully installed"
  }
#+end_src
