#+title: Template
* General approach
1. Set global variables.
2. Override global variables given by options.
3. Reset PATH and other installation relevant exported variables.
4. Check, whether this version is already installed.
   1. If yes, installation is complete.
   2. If not, check if an installation file for the current OS is present.
      1. I yes, install version with this installation file.
      2. If not, download correct installation file and proceed with step 2.1.
5. Clean up the global variables after installation, but not the exported ones.

If something goes wrong, abort. This means, restore the PATH and other global variables:
#+name: definitions
#+begin_src shell :tangle src/setup-template.sh :mkdirp yes :noweb yes :shebang #!/bin/sh :tangle-mode '#o644 :exports none
  <<default_version>>
  <<print_usage>>
  <<init_global_vars>>
  <<reset_global_vars>>
  <<set_vars_from_opts>>
  <<installation_path>>
  <<export_vars>>
  <<restore_exported_vars>>
#+end_src
#+name: execution
#+begin_src shell :tangle src/setup-template.sh :mkdirp yes :noweb strip-export
  init_global_vars
  set_vars_from_opts ${@}
  restore_exported_vars
  export_vars

  echo "TODO: Not yet implemented"
  print_usage

  reset_global_vars
  echo "TMPL successfully installed"
#+end_src

* Overriding of functions
The template can be included into the software specific scripts, where specific functions can be overridden.
*NOTE*: By including scripts, you have to be careful, with execution of scripts, since these are executed during the inclusion and therefore before anything else!

#+begin_src shell :tangle foo.sh
  f1() {
      echo "Foo f1: To override"
  }

  f2() {
      echo "Foo f2: Not to override"
  }

  # To override
  main() {
      f1
      f2
  }

  main
#+end_src
#+begin_src shell :tangle bar.sh
  . foo.sh

  f1() {
      echo "Bar f1: To override"
  }

  f3() {
      f2
      echo "Bar f3: Not to override"
  }

  main() {
      f1
      f3
  }

  main
#+end_src

* Global variables
Each script uses some global variables, like the version to install. These have to be initialized for each run of the script. The initialization of this variables might be the same for all scripts. The only exception is the definition of the [[Default version][default version]], which is described later:
#+name: init_global_vars
#+begin_src shell
  init_global_vars() {
      VERSION=$(default_version)
      INSTALLATION_BASE_DIR=$HOME/opt
      # Reset OPTIND, if getopts was used before
      OPTIND=1
  }
#+end_src

The reset of global variables depends on the initialization. It is necessary to clean up, after the script ran successful or was aborted, because of an error. If ~init_global_vars~ was adopted in a script,  ~reset_global_vars~ variables might need to be adjusted as well:
#+name: reset_global_vars
#+begin_src shell
  reset_global_vars() {
      unset VERSION
      unset INSTALLATION_BASE_DIR
      # Reset OPTIND for future use of getopts
      OPTIND=1
  }
#+end_src

** Default version
Since the strings for version (and therefore default version) are specific to the software, at least the function retrieving the default version has to be adapted in the particular scripts:
#+name: default_version
#+begin_src shell
  default_version() {
      echo tmpl_default-version
  }
#+end_src

** Options
To pass options (like the version to be installed) to the scripts /getopts/ is used:
#+name: set_vars_from_opts
#+begin_src shell
  set_vars_from_opts() {
      while getopts v: opt; do
	  case $opt in
	      v) VERSION=$OPTARG
		 ;;
	  esac
      done
  }
#+end_src
At least the version needs to be set, but other scripts might need additional options. Therefore this method might be overridden.

** Exported variables
The ~PATH~ variable and every other global variable, which is exported by the scripts might exist before the script is run and therefore must be saved and restored, if something goes wrong. In the following example, the ~PATH~ is saved before the new one is exported:
#+name: export_vars
#+begin_src shell
  export_vars() {
      echo "Adding $(installation_path) to PATH"
      SETUP_TMPL_ORIGINAL_PATH="${PATH}"

      export PATH="$(installation_path):${PATH}"
  }
#+end_src
*NOTE*: It is important to have an unique name for the backup variables!

The corresponding reset function restores the ~PATH~ and deletes the backup, to clean up the environment:
#+name: restore_exported_vars
#+begin_src shell
  restore_exported_vars() {
      if [ -v SETUP_TMPL_ORIGINAL_PATH ]; then
	  export PATH="${SETUP_TMPL_ORIGINAL_PATH}"
	  unset SETUP_TMPL_ORIGINAL_PATH
      fi
  }
#+end_src

** Installation path
Since the installation path might be different, depending on the target OS and the software, it is declared as a function, which can be overridden:
#+name: installation_path
#+begin_src shell
  installation_path() {
      echo $INSTALLATION_BASE_DIR/tmpl-$VERSION
  }
#+end_src

* Print usage
Each script must provide a usage information, to explain the valid arguments, options and the default version:
#+name: print_usage
#+begin_src shell
  print_usage() {
      cat <<EOM
  ${0} [-v VERSION]
       -v VERSION Version of TMPL to install.
	  Default: $(default_version)
  EOM
  }
#+end_src
