#+title: Template
This is the template, which defines some common functions for all scripts.

* Usage
The script can be used by executing:
#+begin_src shell :tangle no
  . setup-template.sh [-v VERSION]
#+end_src

** Parameters
*** VERSION
The version you want to install. Defaults to the [[*Default version][default version]].

** Overriding of functions
The template can be included into the software specific scripts, where specific functions can be overridden.

*NOTE*: By including scripts, you have to be careful, with execution of scripts, since these are executed during the inclusion and therefore before anything else!

#+begin_src shell :tangle no
  f1() {
      echo "Foo f1: To override"
  }

  f2() {
      echo "Foo f2: Not to override"
  }

  # To override
  main() {
      f1
      f2
  }

  main
#+end_src
#+begin_src shell :tangle no
  . $(dirname ${BASH_SOURCE[0]})/foo.sh

  f1() {
      echo "Bar f1: To override"
  }

  f3() {
      f2
      echo "Bar f3: Not to override"
  }

  main() {
      f1
      f3
  }

  main
#+end_src

* Implementation
In general, the execution of all scripts follows these common steps:
1. Initialize global custom variables.
2. Override global variables given by options.
3. Check, whether the wanted version is already installed.
4. If not:
   1. Restore PATH and other installation relevant exported variables, which may have been set by a previous installation.
   2. Export PATH and other relevant variables.
   3. Install the wanted version.
5. Clean up the global custom variables and functions after installation, but not the exported ones.
6. Print success message.

If something goes wrong, abort. This means, restore the PATH and other global variables:
#+name: main
#+begin_src shell
  __sp_main() {
      __sp_init_global_vars
      __sp_set_vars_from_opts ${@}

      if ! __sp_is_installed; then
	  echo "Start installation"
	  __sp_restore_exported_vars
	  __sp_export_vars
	  __sp_install || __sp_abort
      fi

      __sp_print_success_message
      __sp_reset_custom_vars_and_funcs
  }
#+end_src
#+name: lib
#+begin_src org :noweb yes :exports none
  <<init_global_vars>>
  <<reset_custom_vars_and_funcs>>
  <<set_vars_from_opts>>
  <<abort>>
  <<local_installation_file_path>>
  <<remote_installation_file_exists>>
  <<download_installation_file>>
  <<install>>
  <<main>>
#+end_src
#+begin_src shell :tangle src/setup-template.sh :mkdirp yes :noweb yes :shebang #!/bin/sh :tangle-mode '#o644 :exports none
  <<lib>>

  <<default_version>>
  <<export_vars>>
  <<restore_exported_vars>>
  <<installation_path>>
  <<is_installed>>
  <<installation_file>>
  <<install_installation_file>>
  <<download_url>>
  <<print_success_message>>

  __sp_main ${@}
#+end_src

** Global variables
Each script uses some custom global variables, like the version to install. These have to be initialized for each run of the script. The initialization of this variables might be the same for all scripts. The only exception is the definition of the [[Default version][default version]], which is described later:
#+name: init_global_vars
#+begin_src shell
  __sp_init_global_vars() {
      __sp_version=$(__sp_default_version)
      __sp_installation_base_dir=$HOME/opt
      # Reset OPTIND, if getopts was used before
      OPTIND=1
  }
#+end_src

Reset all global custom variables and functions. It is necessary to clean up, after the script ran successful or was aborted, because of an error:
#+name: reset_custom_vars_and_funcs
#+begin_src shell
  __sp_reset_custom_vars_and_funcs() {
      unset $(declare | grep '^__sp_' | tr '=' ' ' | cut -f1 -d ' ')
      # Reset OPTIND for future use of getopts
      OPTIND=1
  }
#+end_src

*** Default version
Since the strings for version (and therefore default version) are specific to the software, at least the function retrieving the default version has to be adapted in the particular scripts:
#+name: default_version
#+begin_src shell
  __sp_default_version() {
      echo tmpl_default-version
  }
#+end_src

*** Options
To pass options (like the version to be installed) to the scripts /getopts/ is used:
#+name: set_vars_from_opts
#+begin_src shell
  __sp_set_vars_from_opts() {
      while getopts v: opt; do
	  case $opt in
	      v) __sp_version=$OPTARG
		 ;;
	  esac
      done
  }
#+end_src
At least the version needs to be set, but other scripts might need additional options. Therefore this method might be overridden.

*** Exported variables
The ~PATH~ variable and every other global variable, which is exported by the scripts might exist before the script is run. If something goes wrong during execution, these variables and restored. Therefore, the original values are stored for recovery. At least the variable ~PATH~ must be saved before the new one is exported:
#+name: export_vars
#+begin_src shell
  __sp_export_vars() {
      echo "Add $(__sp_installation_path) to PATH"
      __SP_TMPL_ORIGINAL_PATH="${PATH}"

      export PATH="$(__sp_installation_path):${PATH}"
  }
#+end_src
*NOTE*: It is important to have an unique name for the backup variables!

The corresponding reset function restores the ~PATH~ and deletes the backup, to clean up the environment:
#+name: restore_exported_vars
#+begin_src shell
  __sp_restore_exported_vars() {
      if [ -v __SP_TMPL_ORIGINAL_PATH ]; then
	  export PATH="${__SP_TMPL_ORIGINAL_PATH}"
	  unset __SP_TMPL_ORIGINAL_PATH
      fi
  }
#+end_src

*** Installation path
Since the installation path might be different, depending on the target OS and the software, it is declared as a function, which can be overridden:
#+name: installation_path
#+begin_src shell
  __sp_installation_path() {
      echo $__sp_installation_base_dir/tmpl-$__sp_version
  }
#+end_src

** Check, if wanted version is installed
Before starting the installation, check if the wanted version is already installed. This should usually execute the wanted command and check the output for the correct version. In this template this is just a mock, which returns true, if the given version is ~installed~:
#+name: is_installed
#+begin_src shell
  __sp_is_installed() {
      case "$__sp_version" in
	  installed) return 0
	      ;;
	  ,*) return 1
	      ;;
      esac
  }
#+end_src

** Install wanted version
If the wanted version is not installed, start the installation. This includes the following steps:
1. Check if an installation file for the current OS is present.
   1. If not, download correct installation file and proceed with next step.
      1. If no download file could be found, abort installation with an error message.
2. Install version with this installation file.
#+name: install
#+begin_src shell
  __sp_install() {
      echo "Install version: $__sp_version"

      if [ ! -f $(__sp_local_installation_file_path) ]; then
	  echo "Local installation file not found: $(__sp_local_installation_file_path). Try, download new one"
	  if __sp_remote_installation_file_exists; then
	      __sp_download_installation_file
	  else
	      echo "ERROR: No remote installation file found. Abort"
	      __sp_abort
	  fi
      fi
      __sp_install_installation_file
   }
#+end_src

*** Installation file
The name of the installation file is specific to the software, its version and the target OS. Therefore a specific implementation is needed. For the template a dummy is used:
#+name: installation_file
#+begin_src shell
  __sp_installation_file() {
      echo installation.file
  }
#+end_src

*** Local installation file path
The path to the local installation file. The default location is in the ~/tmp/~ directory:
#+name: local_installation_file_path
#+begin_src shell
  __sp_local_installation_file_path() {
      echo /tmp/$(__sp_installation_file)
  }
#+end_src

*** Install installation file
The installation of the local installation file is specific to the software. For the template a dummy is used:
#+name: install_installation_file
#+begin_src shell
  __sp_install_installation_file() {
      echo "Install installation file"
	  case "$__sp_version" in
	  installation_fail) return 1
	     ;;
	  ,*) return 0
	     ;;
      esac
  }
#+end_src

*** Check, if remote installation file exists
Before downloading the installation file, check if it exists:
#+name: remote_installation_file_exists
#+begin_src shell
  __sp_remote_installation_file_exists() {
      curl -sIf $(__sp_download_url) >/dev/null
  }
#+end_src

*** Download URL
The download URL is specific to the software. For the template a dummy implementation is used:
#+name: download_url
#+begin_src shell
  __sp_download_url() {
      case "$__sp_version" in
	  download_fail) echo https://github.com/aaron-kunde/setup-project/blob/main/non-existing.file
	     ;;
	  ,*) echo https://github.com/aaron-kunde/setup-project/blob/main/README.org
	     ;;
      esac
  }
#+end_src

*** Download installation file
If a remote installation file was found, download it:
#+name: download_installation_file
#+begin_src shell
  __sp_download_installation_file() {
      echo "Download installation file"
      curl $(__sp_download_url) -o $(__sp_local_installation_file_path)
  }
#+end_src

** Abort installation
During the installation process, several errors can occurs, which cause the need to abort the installation process. If the process needs to be aborted, all global variables need to be reset, as if the installation process never had been started:
#+name: abort
#+begin_src shell
  __sp_abort() {
      __sp_restore_exported_vars

      return 0
  }
#+end_src

** Print success message
The success message depends on the installed software and must be implemented specific:
#+name: print_success_message
#+begin_src shell
  __sp_print_success_message() {
      echo "TMPL successfully installed"
  }
#+end_src

* Tests
** Execute
#+begin_src shell
  test/bats/bin/bats -t test/test-template.bats
#+end_src

The following tests are OS independent:
#+begin_src bats :tangle test/test-template.bats :mkdirp yes :noweb strip-export :shebang #!/usr/bin/env bats :tangle-mode '#o644 :exports none
  __SP_TESTEE=src/setup-template.sh

  <<setup>>
  <<teardown>>

  <<Environment must be clean after execution if succeeds with default version>>
  <<Environment must be clean after execution if succeeds with given version>>
  <<Environment must be clean after execution if installation fails>>
  <<Should only print success message if version is already installed>>
  <<Should not alter environment if installation fails>>
  <<Must print error message if remote installation file not found>>
  <<Should try download if local installation file not exists>>
  <<Should try download if remote installation file exists>>
#+end_src

The following tests are specific for different OS:
#+begin_src bats :tangle test/test-template.bats :mkdirp yes :noweb strip-export :shebang #!/usr/bin/env bats :tangle-mode '#o644 :exports none
  <<Must print versions to install with default version>>
  <<Must print versions to install with given version>>
  <<Should export variables if succeeds with default version>>
  <<Should export variables if succeeds with given version>>
  <<Should not alter environment if version is already installed>>
  <<Must print success message if installation succeeds with default version>>
  <<Must print success message if installation succeeds with given version>>
  <<Should not try download if local installation file exists>>
#+end_src

Each test needs a setup, which loads the necessary Bats libraries:
- [[https://github.com/bats-core/bats-support][bats-support]]
- [[https://github.com/bats-core/bats-assert][bats-assert]]
- [[https://github.com/bats-core/bats-file][bats-file]]

Furthermore, the exported variables are backed up. In this case at least the ~PATH~:
#+name: setup
#+begin_src bats
  setup() {
    load 'test_helper/bats-support/load'
    load 'test_helper/bats-assert/load'
    load 'test_helper/bats-file/load'

    __SP_TEST_ORIGINAL_PATH="$PATH"
  }
#+end_src

To clean up, the exported variables are reset to its saved values after each test:
#+name: teardown
#+begin_src bats
  teardown() {
      PATH="$__SP_TEST_ORIGINAL_PATH"

      # Assert, no custom variable or function is set
      declare | grep -e '^__sp_'
      assert_equal $? 1
  }
#+end_src

** Test cases

*** Must print version and path to install
If wanted version is not the current, print the version to be installed and the path to be added.
**** With default version
#+name: Must print versions to install with default version
#+begin_src bats
  @test "Must print versions to install with default version" {
      run . $__SP_TESTEE

      assert_line 'Install version: tmpl_default-version'
      assert_line "Add $HOME/opt/tmpl-tmpl_default-version to PATH"

      rm /tmp/installation.file
  }
#+end_src

**** With given version
#+name: Must print versions to install with given version
#+begin_src bats
  @test "Must print versions to install with given version" {
      run . $__SP_TESTEE -v some_other-version

      assert_line 'Install version: some_other-version'
      assert_line "Add $HOME/opt/tmpl-some_other-version to PATH"

      rm /tmp/installation.file
  }
#+end_src

*** Environment must be clean after execution

**** If succeeds with default version
After the script has run without a given version, the newly introduced global variables shall not be set and ~$OPTIND~ must be ~1~:
#+name: Environment must be clean after execution if succeeds with default version
#+begin_src bats
  @test "Environment must be clean after execution if succeeds with default version" {
      . $__SP_TESTEE

      assert_equal $OPTIND 1

      rm /tmp/installation.file
  }
#+end_src

**** If succeeds with given version
After the script has run with a given version, the newly introduced global variables shall not be set and ~$OPTIND~ must be ~1~:
#+name: Environment must be clean after execution if succeeds with given version
#+begin_src bats
  @test "Environment must be clean after execution if succeeds with given version" {
      . $__SP_TESTEE -v some_other-version

      assert_equal $OPTIND 1

      rm /tmp/installation.file
  }
#+end_src

**** If installation fails
After the script failed, the newly introduced global variables shall not be set and ~$OPTIND~ must be ~1~:
#+name: Environment must be clean after execution if installation fails
#+begin_src bats
  @test "Environment must be clean after execution if installation fails" {
      . $__SP_TESTEE -v installation_fail

      assert_equal $OPTIND 1

      rm /tmp/installation.file
  }
#+end_src

*** Should export variables
The exported ~$PATH~ must be extended with the wanted version.

**** If succeeds with default version

#+name: Should export variables if succeeds with default version
#+begin_src bats
  @test "Should export variables if succeeds with default version" {
      . $__SP_TESTEE

      assert_equal "$PATH" "$HOME/opt/tmpl-tmpl_default-version:$__SP_TEST_ORIGINAL_PATH"

      rm /tmp/installation.file
  }
#+end_src

**** If succeeds with given version

#+name: Should export variables if succeeds with given version
#+begin_src bats
  @test "Should export variables if succeeds with given version" {
      . $__SP_TESTEE -v some_other-version

      assert_equal "$PATH" "$HOME/opt/tmpl-some_other-version:$__SP_TEST_ORIGINAL_PATH"

      rm /tmp/installation.file
  }
#+end_src

*** Should only print success message, if version is already installed
If the given (or default) version is already installed, only a success message should be shown:
#+name: Should only print success message if version is already installed
#+begin_src bats
  @test "Should only print success message if version is already installed" {
      run . $__SP_TESTEE -v installed

      refute_line -p "Add $HOME/opt/"
      refute_line -p 'Install version: '
      assert_line 'TMPL successfully installed'

      assert_file_not_exists /tmp/installation.file
  }
#+end_src

*** Should not alter environment, if version is already installed
If the given (or default) version is already installed, the environment should not be altered:
#+name: Should not alter environment if version is already installed
#+begin_src bats
  @test "Should not alter environment if version is already installed" {
      PATH="/some/new/path:$__SP_TEST_ORIGINAL_PATH"

      . $__SP_TESTEE -v installed

      assert_equal $OPTIND 1
      assert_equal "$PATH" "/some/new/path:$__SP_TEST_ORIGINAL_PATH"

      assert_file_not_exists /tmp/installation.file
  }
#+end_src

*** Should not alter environment, if installation fails
After the script failed, the exported ~$PATH~ must not be altered:
#+name: Should not alter environment if installation fails
#+begin_src bats
  @test "Should not alter environment if installation fails" {
      . $__SP_TESTEE -v installation_fail

      assert_equal "$PATH" "$__SP_TEST_ORIGINAL_PATH"

      rm /tmp/installation.file
  }
#+end_src

*** Must print success message, if installation succeeds
If successful, a success message must be printed.

**** With default version
#+name: Must print success message if installation succeeds with default version
#+begin_src bats
  @test "Must print success message if installation succeeds with default version" {
      run . $__SP_TESTEE

      assert_line 'TMPL successfully installed'

      rm /tmp/installation.file
  }
#+end_src

**** With given version
#+name: Must print success message if installation succeeds with given version
#+begin_src bats
  @test "Must print success message if installation succeeds with given version" {
      run . $__SP_TESTEE -v some_other-version

      assert_line 'TMPL successfully installed'

      rm /tmp/installation.file
  }
#+end_src

*** Must print error message, if remote installation file not found
#+name: Must print error message if remote installation file not found
#+begin_src bats
  @test "Must print error message if remote installation file not found" {
      run . $__SP_TESTEE -v download_fail

      assert_line 'Install version: download_fail'
      assert_line 'Local installation file not found: /tmp/installation.file. Try, download new one'
      assert_line 'ERROR: No remote installation file found. Abort'
      # TODO: Should not be shown in real scripts
      # refute_line 'TMPL successfully installed'

      assert_file_not_exists /tmp/installation.file
  }
#+end_src

*** Should try download

**** If local installation file not exists
#+name: Should try download if local installation file not exists
#+begin_src bats
  @test "Should try download if local installation file not exists" {
      run . $__SP_TESTEE

      assert_line 'Local installation file not found: /tmp/installation.file. Try, download new one'
      assert_line 'Download installation file'

      rm /tmp/installation.file
  }
#+end_src

**** If remote installation file exists
#+name: Should try download if remote installation file exists
#+begin_src bats
  @test "Should try download if remote installation file exists" {
      run . $__SP_TESTEE

      assert_line 'Download installation file'

      rm /tmp/installation.file
  }
#+end_src

*** Should not try download, if local installation file exists
#+name: Should not try download if local installation file exists
#+begin_src bats
  @test "Should not try download if local installation file exists" {
      touch /tmp/installation.file

      run . $__SP_TESTEE

      refute_line 'Local installation file not found: /tmp/installation.file. Try, download new one'
      refute_line 'Download installation file'

      rm /tmp/installation.file
  }
#+end_src
