name: 'Test setup scripts'

on:
  # Run this workflow, whenever something is pushed
  push:
  # Run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test_template:
    name: Test setup-template
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Bats and Bats libs
        uses: bats-core/bats-action@2.0.0
        with:
          support-path: ${{ github.workspace }}/test/test_helper/bats-support
          assert-path: ${{ github.workspace }}/test/test_helper/bats-assert
          file-path: ${{ github.workspace }}/test/test_helper/bats-file
      - name: Run template tests
        run: bats -t test/test-template.bats
