name: 'Test setup scripts'

on:
  # Run this workflow, whenever something is pushed
  push:
  # Run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test_scripts_linux:
    name: Test setup-scripts on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Bats and Bats libs
        uses: bats-core/bats-action@2.0.0
        with:
          support-path: ${{ github.workspace }}/test/test_helper/bats-support
          assert-path: ${{ github.workspace }}/test/test_helper/bats-assert
          file-path: ${{ github.workspace }}/test/test_helper/bats-file
      - name: Run tests for Template
        run: bats -t test/test-template.bats
      - name: Run OS indenpendent tests for Node.js
        run: bats -t test/test-nodejs.bats
      - name: Run Linux specific tests for Node.js
        run: bats -t test/test-nodejs.linux.bats

  test_scripts_windows:
    name: Test setup-scripts on Windows with MinGW
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Run tests for Template
        run: test/bats/bin/bats -t test/test-template.bats
      - name: Run OS indenpendent tests for Node.js
        run: test/bats/bin/bats -t test/test-nodejs.bats
      - name: Run Windows specific tests for Node.js
        run: test/bats/bin/bats -t test/test-nodejs.win.bats
